import type { Metadata } from "next";
import { fontMono, fontPixelSquare, fontSans } from "@/lib/fonts"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import PageTransition from '@/components/pageTransition'
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Prateek Sagar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    className={cn(
      fontMono.variable,
      fontSans.variable,
      fontPixelSquare.variable
    )}
    suppressHydrationWarning
    >
      <body
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <PageTransition>
          {children}
          </PageTransition>
          <Toaster />
          </ThemeProvider>
      </body>
    </html>
  );
}
